[package]
name = "nxpf"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui_extras = { version = "0.22", features = ["image"] }
env_logger = "0.10.0"
image = { version = "0.24", default-features = false, features = ["png"] }
flate2 = "1.0"
winreg = { version = "0.10", optional = false }

[[bin]]
name = "nxpf"
path = "main.rs"
